[server]
maxUploadSize = 50
enableXsrfProtection = false
enableCORS = false
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
serverPort = 7860
gatherUsageStats = false

[runner]
fastReruns = true
